services:
  cphalcon:
    container_name: cphalcon
    build: .
    # env_file:
    #   - .env
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - cphalcon_db

  cphalcon_db:
    image: mysql:latest
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: "#"
      MYSQL_DATABASE: "#"
      MYSQL_USER: "#"
      MYSQL_PASSWORD: "#"
    volumes:
      - cphalcon_dbdata:/var/lib/mysql


  cphalcon_nginx:
    image: nginx:latest
    restart: always
    container_name: cphalcon_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cphalcon_nginx.entrypoints=web"
      - "traefik.http.routers.cphalcon_nginx.rule=Host(`domain.localhost`)"
      - "traefik.http.services.cphalcon_nginx.loadbalancer.server.port=80"
    volumes:
      - ./src:/usr/src/app
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx/
    depends_on:
      - cphalcon


volumes:
  cphalcon_dbdata:
  
networks:
  default:
    external: true
    name: network

      
